apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-writer
  namespace: proj12-dev
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: log-writer
            image: python:3.10-slim
            command: ["python", "-c", "import datetime; print('📌 Log:', datetime.datetime.now())"]
          restartPolicy: OnFailure
