apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: proj12-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: taimoordevops/proj12-flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: env
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: secret_key
